# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9c707aee131683589c4e31d936409f892db4c5fe8cfc9f05a74fc15cc65e278e452d40a73de74cddb0719ef91c4bb0ba2926b25a1d31d8ba09a37074dfc4ffc

test:
  secret_key_base: fb67858ffca5319370bc4b32a872979d27132acb653db9ae2d2acd94a544a518af1a4d7a54b5084da54579980932077da963bdee6dd898369c3c316b88b37a99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
